version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/upstream"
    schedule:
      interval: "weekly"
    reviewers:
      - "az-digital/developers"
    open-pull-requests-limit: 10
