name: Create PR for new Arizona Quickstart Release
on:
  repository_dispatch:
    types: az_quickstart_release

jobs:
  release:
    name: Create PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create new branch and PR
        run: |
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config --global user.name "${GITHUB_ACTOR}"
          git checkout -b 'az-quickstart-${{ github.event.client_payload.version }}'
          jq --indent 4 '.require."az-digital/az_quickstart" |= "${{ github.event.client_payload.version }}"' upstream/composer.json > upstream/composer.json.new
          mv upstream/composer.json.new upstream/composer.json
          git add upstream/composer.json
          git commit -m 'Update Arizona Quickstart to ${{ github.event.client_payload.version }}'
          git push --set-upstream origin 'az-quickstart-${{ github.event.client_payload.version }}'
          echo "${{ secrets.REPO_DISPATCH_TOKEN }}" | gh auth login --with-token
          gh pr create --title 'Update Arizona Quickstart to ${{ github.event.client_payload.version }}' --body 'Release Notes: https://github.com/az-digital/az_quickstart/releases/tag/${{ github.event.client_payload.version }}'
